### ISSUE TITLE
Cannot get this running - maybe Gender API key issue?

### ISSUE THREAD

**Issue by smweis** [mb3152/balanced_citer#1]
Looks like the readme and example calls for -gender_key to be passed, but the script asks for -myKey? Is that the same thing? 

And I wasn't sure what to input for the gender_key. I set up an account with gender-api.com and got a key to use (a string of characters). Is that all I have to input in the call. Here's my call: 

I used conda on Windows 10. 

`python unbiasedciter.py -authors 'Weisberg' -bibfile "C:\Users\smwei\Desktop\Splash\CogNeuro_Grad.bib" -myKey 'rWzoCS[redacted]' -homedir 'C:\Users\smwei\Documents\balanced_citer\'`

And the error I get: 

```
Traceback (most recent call last):
  File "unbiasedciter.py", line 83, in <module>
    with open(homedir + 'gender_base' + '.pkl', 'rb') as f:
OSError: [Errno 22] Invalid argument: "'C:\\Users\\smwei\\Documents\\balanced_citer\\'gender_base.pkl"
```

**Comment by mb3152** [comment]
Good catch, I just fixed this! Should run now...

**Comment by smweis** [comment]
Yep, I think I just made parallel fixes and got it working. Also, in Windows, the quotes are very important...

`python unbiasedciter.py -authors "Steven Weisberg Steve Weisberg" -bibfile "C:\Users\smwei\Desktop\Splash\CogNeuro_Grad.bib" -gender_key 'redacted' -homedir C:\Users\smwei\Documents\balanced_citer\data\`

Also, note I have to call the home directory with /data added on...

And now I get: 

```
Traceback (most recent call last):
  File "unbiasedciter.py", line 201, in <module>
    expected = np.load('/%s/data/expected_matrix_wiki.npy'%(homedir))
  File "C:\Users\smwei\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
OSError: [Errno 22] Invalid argument: '/C:\\Users\\smwei\\Documents\\balanced_citer\\data\\/data/expected_matrix_wiki.npy'
```

**Comment by mb3152** [comment]
Weird, does windows use \ and OS use / ?

**Comment by smweis** [comment]
Yes - it's a real nightmare crossing operating systems. matlab has fullfile('path','to','dir') which returns '/path/to/home' in mac and '\path\to\home' in Windows. I'll modify my local copy (os_fspath is likely the culprit now that I'm looking at it again.

**Comment by mb3152** [comment]
Okay I’ll figure out a fix! If you know of one and end up fixing it let us know. 

Max Bertolero, PhD
Post-Doctoral Scientist
University of Pennsylvania
Department of Bioengineering
Complex Systems Lab
maxbertolero.org | complexsystemsupenn.com

**Comment by smweis** [comment]
More of a workaround - which did work! I deleted out the /data/ part of the directory in the two calls. I've attached my local copy because I don't want to do a pull request. I'd suggest allowing people to put whatever they like in for their home directory (inside the repo, or perhaps the same directory as their .bib file is.) Then you could add a directory (figs) within that and save all figs there (perhaps with the name of the .bib file, so it can be easily associated)?  That way it'd also be easier to save the figure - it would be overwritten each time I run the same .bib file, but not every time I run the script. 

This is great code! I hope these make it a little more usable :) 


So lines 201 and 214 were adjusted like so: 

`plt.savefig('%srace_gender_citations.pdf'%(homedir))
`
